### ISSUE TITLE
Add double quotes for column name

### ISSUE THREAD

**Issue by changvvb** [scalikejdbc/scalikejdbc#1058]
Add double quotes for column name, otherwise may conflict with reserved keyword.

`org.postgresql.util.PSQLException: ERROR: syntax error at or near "limit"
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468) ~[postgresql-42.2.6.jar:42.2.6]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211) ~[postgresql-42.2.6.jar:42.2.6]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309) ~[postgresql-42.2.6.jar:42.2.6]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) ~[postgresql-42.2.6.jar:42.2.6]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) ~[postgresql-42.2.6.jar:42.2.6]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149) ~[postgresql-42.2.6.jar:42.2.6]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124) ~[postgresql-42.2.6.jar:42.2.6]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.3.1.jar:?]
	at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.executeUpdate(DBConnectionAttributesWiredPreparedStatement.scala:80) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor.$anonfun$executeUpdate$1(StatementExecutor.scala:400) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23) ~[scala-library.jar:?]
	at scalikejdbc.StatementExecutor$NakedExecutor.apply(StatementExecutor.scala:22) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLAndTiming$$super$apply(StatementExecutor.scala:376) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply(StatementExecutor.scala:320) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor$LoggingSQLAndTiming.apply$(StatementExecutor.scala:306) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor$$anon$1.scalikejdbc$StatementExecutor$LoggingSQLIfFailed$$super$apply(StatementExecutor.scala:376) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply(StatementExecutor.scala:353) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply$(StatementExecutor.scala:352) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:376) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.StatementExecutor.executeUpdate(StatementExecutor.scala:400) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession$.$anonfun$executeUpdate$1(DBSession.scala:798) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession$.$anonfun$executeUpdate$1$adapted(DBSession.scala:798) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession.$anonfun$updateWithFiltersInternal$1(DBSession.scala:537) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:18) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.ActiveSession.using(DBSession.scala:837) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession.updateWithFiltersInternal(DBSession.scala:535) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession.updateWithFilters(DBSession.scala:477) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession.updateWithFilters$(DBSession.scala:466) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:837) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession.updateAndReturnSpecifiedGeneratedKey(DBSession.scala:664) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSession.updateAndReturnSpecifiedGeneratedKey$(DBSession.scala:635) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.ActiveSession.updateAndReturnSpecifiedGeneratedKey(DBSession.scala:837) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSessionWrapper.$anonfun$updateAndReturnSpecifiedGeneratedKey$1(DBSessionWrapper.scala:92) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSessionWrapper.$anonfun$updateAndReturnSpecifiedGeneratedKey$1$adapted(DBSessionWrapper.scala:92) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSessionWrapper.$anonfun$withAttributesSwitchedDBSession$1(DBSessionWrapper.scala:34) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:33) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.DBSessionWrapper.updateAndReturnSpecifiedGeneratedKey(DBSessionWrapper.scala:92) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.SQLUpdateWithGeneratedKey.$anonfun$apply$20(SQL.scala:779) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.SQLUpdateWithGeneratedKey.$anonfun$apply$20$adapted(SQL.scala:779) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
	at scalikejdbc.SQLUpdateWithGeneratedKey.apply(SQL.scala:786) ~[scalikejdbc-core_2.12-3.3.5.jar:3.3.5]
`

**Comment by seratch** [comment]
I'm interested in implementing a feature to configure to automatically double-quote or back quote to columns in a statement. We don't have a release date for it yet, though.

As a workaround at this moment, you can go with overriding `columns` as below:

```sql
object Something extends SQLSyntaxSupport[Something] {
  override val columns = Seq("id", "name", "`limit`")
}
```

**Comment by changvvb** [comment]
Thanks @seratch , I will try this workaround later.
