### ISSUE TITLE
scalikejdbc-test 3.4.2 AutoRollback seems not support scalatest 3.1.0

### ISSUE THREAD

**Issue by tanvn** [scalikejdbc/scalikejdbc#1090]
Hello,
Today I was trying to upgrade scalikejdbc from 3.4.0 to 3.4.2 in my project.
And when I try to run integration test to make sure everything work as expected, I got the error :

```
[error] java.lang.NoSuchMethodError: scalikejdbc.scalatest.AutoRollback.withFixture$(Lscalikejdbc/scalatest/AutoRollback;Lorg/scalatest/FixtureTestSuite$OneArgTest;)Lorg/scalatest/Outcome;
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.invokeWithFixture$1(FixtureAnyWordSpecLike.scala:1217)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.$anonfun$runTest$1(FixtureAnyWordSpecLike.scala:1228)
[error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.runTest(FixtureAnyWordSpecLike.scala:1228)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.runTest$(FixtureAnyWordSpecLike.scala:1209)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpec.runTest(FixtureAnyWordSpec.scala:232)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.$anonfun$runTests$1(FixtureAnyWordSpecLike.scala:1271)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[error] 	at scala.collection.immutable.List.foreach(List.scala:305)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.runTests(FixtureAnyWordSpecLike.scala:1271)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.runTests$(FixtureAnyWordSpecLike.scala:1270)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpec.runTests(FixtureAnyWordSpec.scala:232)
[error] 	at org.scalatest.Suite.run(Suite.scala:1112)
[error] 	at org.scalatest.Suite.run$(Suite.scala:1094)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpec.org$scalatest$wordspec$FixtureAnyWordSpecLike$$super$run(FixtureAnyWordSpec.scala:232)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.$anonfun$run$1(FixtureAnyWordSpecLike.scala:1292)
[error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.run(FixtureAnyWordSpecLike.scala:1292)
[error] 	at org.scalatest.wordspec.FixtureAnyWordSpecLike.run$(FixtureAnyWordSpecLike.scala:1291)

````

Then I found out source code of AutoRollback file in the scalikejdbc-test_2.13-3.4.2.jar is not containing the latest commits as the master branch.

- Tag 3.4.2: https://github.com/scalikejdbc/scalikejdbc/blob/3.4.2/scalikejdbc-test/src/main/scala/scalikejdbc/scalatest/AutoRollback.scala#L32

- Master branch: https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-test/src/main/scala/scalikejdbc/scalatest/AutoRollback.scala#L31

So could you guys please confirm whether scalikejdbc-test 3.4.2 is supporting scalatest 3.1.0 ?
If not, may I know where it will be supported ? (If it already is, may be I am missing something with my project's settings and I am hoping I am not)

Best regards,

**Comment by tanvn** [comment]
After reading [CONTRIBUTING](https://github.com/scalikejdbc/scalikejdbc/blob/master/CONTRIBUTING.md )  and 
<img width="1050" alt="スクリーンショット 2020-05-18 18 14 30" src="https://user-images.githubusercontent.com/3862870/82195718-a511a400-9933-11ea-9007-35379c46107b.png">

the `71 commits to master since this release` now I understood that in 3.4.2 release scalatest 3.1.0 is not supported yet and maybe it will be supported from 3.5.x

I'm sorry for the disturbance.
