### ISSUE TITLE
NamedDB ConnectionPool error with QueryDSL

### ISSUE THREAD

**Issue by piccell** [scalikejdbc/scalikejdbc#1103]
Hi,

Using version 3.5.0, I have an error when using QueryDSL style with a NamedDB, while everything is fine with SQLInterpolation.
I am not sure if it is a bug or something I am missing in the class definition...

Running Teliway.findAll is fine.
Running Teliway.findAll2 throws the following exception:

Thanks for your help.

```
java.lang.IllegalStateException: Connection pool is not yet initialized.(name:pool1)
  at scalikejdbc.ConnectionPool$.$anonfun$get$1(ConnectionPool.scala:78)
  at scala.collection.mutable.HashMap.getOrElse(HashMap.scala:416)
  at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:76)
  at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:66)
  at scalikejdbc.NamedDB.connectionPool(NamedDB.scala:25)

```
Here is the code :

```
case class Teliway(id:Int)

object Teliway extends SQLSyntaxSupport[Teliway]
{
   override def connectionPoolName:Any = "pool1"
   override def tableName: String = "teliways" 

   def bind(rn:ResultName[Teliway])(rs:WrappedResultSet) = Teliway(rs.get(rn.id))

   def findAll = NamedDB(Symbol("pool1")) readOnly { implicit session =>
      sql"select id from teliways".map(_.int(1)).list().apply()
   }

   def findAll2 = NamedDB(Symbol("pool1")) readOnly { implicit session =>
      val tlw = Teliway.syntax
      withSQL {
         select.from(Teliway as tlw)
      }
      .map(bind(tlw.resultName))
      .list().apply()
   }   
}
```

**Comment by piccell** [comment]
my error...
override def connectionPoolName:Any = "pool1"
should have been
override def connectionPoolName:Any = Symbol("pool1")
