### ISSUE TITLE
Scala 3: autoNamedValues errors

### ISSUE THREAD

**Issue by greenhost87** [scalikejdbc/scalikejdbc#1255]
When you try to use `autoNamedValues` on Scala 3  when your model is `case class Test` and `object Test extends SQLSyntaxSupport[Test]` compilation failed with error 

```
[error]    |Exception occurred while executing macro expansion.
[error]    |java.lang.AssertionError: assertion failed: The symbol `apply` is overloaded. The method Select.unique can only be used for non-overloaded symbols.
[error]    |    at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]    |    at scala.quoted.runtime.impl.QuotesImpl$reflect$Select$.unique(QuotesImpl.scala:457)
[error]    |    at scala.quoted.runtime.impl.QuotesImpl$reflect$Select$.unique(QuotesImpl.scala:455)
[error]    |    at scalikejdbc.autoNamedValues$$anon$1.applyOrElse(autoNamedValues.scala:25)
[error]    |    at scalikejdbc.autoNamedValues$$anon$1.applyOrElse(autoNamedValues.scala:17)
[error]    |    at scala.collection.immutable.List.collect(List.scala:267)
[error]    |    at scalikejdbc.autoNamedValues$.apply_impl(autoNamedValues.scala:36)
```

**Comment by seratch** [comment]
I tried to reproduce your issue with the following example app but it successfully compiles.

```sbt
// build.sbt
val scala3Version = "3.0.1-RC2" // verified with 3.0.0, 3.0.1-RC1 too

lazy val root = project
  .in(file("."))
  .settings(
    name := "scala3-simple",
    version := "0.1.0",
    scalaVersion := scala3Version,
    libraryDependencies ++= Seq(
      "com.h2database"  %  "h2" % "1.4.200",
      "org.scalikejdbc" %% "scalikejdbc" % "4.0.0-RC2",
      "org.scalikejdbc" %% "scalikejdbc-syntax-support-macro" % "4.0.0-RC2"
    )
  )
```

```scala
import scalikejdbc._

case class Organization(id: Long, websiteUrl: String)

object Organization extends SQLSyntaxSupport[Organization] {
  def apply(s: SyntaxProvider[Organization])(rs: WrappedResultSet): Organization = autoConstruct(rs, s)
  def apply(r: ResultName[Organization])(rs: WrappedResultSet): Organization = autoConstruct(rs, r)
}

@main def main = {
  Class.forName("org.h2.Driver")
  ConnectionPool.singleton("jdbc:h2:mem:hello", "user", "pass")
  DB autoCommit { implicit s =>
    sql"create table organization (id int not null, website_url varchar(256))".execute.apply()
  }

  val o = new Organization(1L, "http://www.example.com/")
  val oc = Organization.column
  val q = insert.into(Organization).namedValues(autoNamedValues(o, oc))
  println(q)
}
```

Can you share a minimum working example that reproduces the error?

**Comment by greenhost87** [comment]
Hm... currently I can't reproduce that problem. Now I close that issue
