### ISSUE TITLE
Connection Link Failure

### ISSUE THREAD

**Issue by Swapnil1248** [scalikejdbc/scalikejdbc#1741]
We have recently upgraded from `scalikejdbc` from 2.3.0 to 2.5.0 and seeing intermittent `Connection Link Failure`.

```
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 930,132 milliseconds ago.  The last packet sent successfully to the server was 930,134 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor40.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3661)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2417)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4846)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:544)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:544)
	at scalikejdbc.ActiveSession.<init>(DBSession.scala:728)
	at scalikejdbc.DBSession$.apply(DBSession.scala:694)
	at scalikejdbc.DBConnection.readOnlySession(DBConnection.scala:190)
	at scalikejdbc.DBConnection.readOnlySession$(DBConnection.scala:184)
	at scalikejdbc.DB.readOnlySession(DB.scala:60)
	at scalikejdbc.DBConnection.$anonfun$readOnly$1(DBConnection.scala:201)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:18)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16)
	at scalikejdbc.DB.using(DB.scala:60)
	at scalikejdbc.DBConnection.readOnly(DBConnection.scala:201)
	at scalikejdbc.DBConnection.readOnly$(DBConnection.scala:200)
	at scalikejdbc.DB.readOnly(DB.scala:60)
```	
ConnectionPool properties
```
  initialSize=5
  maxSize=10
  connectionTimeoutMillis=2000
  validationQuery="select 1 as one"
  connectionPoolFactoryName="commons-dbcp2"
  driverName="com.custom.driver"
  serverTimezone="America/Chicago"
  additionalFlags=[
    "useSSL=false",
    "useLegacyDatetimeCode=false",
    "jdbcCompliantTruncation=false"
  ]

  limitConnections=false
 
```

**Comment by seratch** [comment]
Hi @Swapnil1248, ScalikeJDBC does not do anything about the underlying connection management. Perhaps, upgrading either the connection pool library or MySQL JDBC driver may be a direct cause of your situation.

**Comment by Swapnil1248** [comment]
```
  // To fix MS SQLServer jtds driver issue
  // https://github.com/scalikejdbc/scalikejdbc/issues/461
  if (Option(settings.validationQuery).exists(_.trim.nonEmpty)) {
    _pool.setTestOnBorrow(true)
  }
  ```
  
  ValidationQuery was missing in ConnectionPoolSetting. Add one fixed it. Thanks!
