### ISSUE TITLE
Using non-typed Null for PreparedStatement.setObject cause an error with Sybase sql server.

### ISSUE THREAD

**Issue by kalinichenko** [scalikejdbc/scalikejdbc#195]
```
java.sql.SQLException: JZ0SE: Invalid object type (or null object) specified for setObject().
    at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(ErrorMessage.java:765)
    at com.sybase.jdbc4.jdbc.SybPreparedStatement.setObject(SybPreparedStatement.java:1247)
    at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:169)
    at org.apache.commons.dbcp.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:169)
    at scalikejdbc.StatementExecutor$$anonfun$bindParams$3.apply(StatementExecutor.scala:77)
    at scalikejdbc.StatementExecutor$$anonfun$bindParams$3.apply(StatementExecutor.scala:75)
    at scalikejdbc.StatementExecutor.bindParams(StatementExecutor.scala:75)
    at scalikejdbc.StatementExecutor.initialize(StatementExecutor.scala:59)
    at scalikejdbc.StatementExecutor.<init>(StatementExecutor.scala:53)
    at scalikejdbc.DBSession$class.createStatementExecutor(DBSession.scala:65)
    at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:308)
    at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:420)
    at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:290)
    at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:420)
    at scalikejdbc.SQLUpdate.apply(SQL.scala:460)
    at models.Employee$.create(Employee.scala:134)
    at models.EmployeeSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(EmployeeSpec.scala:43)
    at models.EmployeeSpec$$anonfun$1$$anonfun$apply$1$$anon$1.delayedInit(EmployeeSpec.scala:42)
    at models.EmployeeSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(EmployeeSpec.scala:42)
    at models.EmployeeSpec$$anonfun$1$$anonfun$apply$1.apply(EmployeeSpec.scala:42)
    at models.EmployeeSpec$$anonfun$1$$anonfun$apply$1.apply(EmployeeSpec.scala:42)
```

**Comment by dgrene** [comment]
hi @kalinichenko , could you please tell me how you resolved this issue with sybase.I am still struggling with that

**Comment by pariskapoor** [comment]
Hi All,

I had the same issue. In sybase procedure we set as 
@contrlnum          int = null

While in JAVA callable  statement. how to set null by default. We tried setNull, setObject and setString but not working. Any idea please help.
