### ISSUE TITLE
Batch Insert Raising java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by janihur** [scalikejdbc/scalikejdbc#30]
I'm getting constantly the following exception when I'm executing a batch insert (1.3.2):

```
java.lang.IndexOutOfBoundsException: 0
at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:51)
at scala.collection.immutable.List.apply(List.scala:45)
at scalikejdbc.StatementExecutor$$anonfun$scalikejdbc$StatementExecutor$$sqlString$1.apply(StatementExecutor.scala:111)
at scalikejdbc.StatementExecutor$$anonfun$scalikejdbc$StatementExecutor$$sqlString$1.apply(StatementExecutor.scala:108)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
at scala.collection.immutable.StringOps.foreach(StringOps.scala:31)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
at scala.collection.immutable.StringOps.map(StringOps.scala:31)
...
```

My production code is essentially like this simple ScalaTest example that runs without problems:

```
  case class Item(id: Long, desc: String, amount: Int)

  test("4") {
    val values = List(Item(100, "item 100", 100),
                      Item(101, "item 101", 101))

    info(values.toString)

    val values2 = values.map {
      i ⇒ Seq(400, i.desc, i.amount)
    }

    info(values2.toString)

    DB localTx { implicit session ⇒
      SQL("""insert into test(id, data1, data2) values(?, ?, ?)""").batch(values2: _*).apply()
    }
  }
```

As I've not yet succeeded to narrow down the issue this might be just an indication of a problem in some other parts of my system.

**Comment by JBetz** [comment]
I'm experiencing the same issue in version 2.5.2:

```
sql"INSERT INTO $database.cs_api_scan_log (log_uid, `key`, `value`, shortdate) VALUES (?, ?, ?, ?)"
   .batch(log.pairs.map(pair => Seq(id, pair._1, pair._2, "now()")).toSeq)
   .apply[Seq]()
   .sum[Int]
})
```

Throws:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
	at com.mysql.jdbc.PreparedStatement.setBinaryStream(PreparedStatement.java:3269)
	at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:4392)
	... 85 more
```

**Comment by JBetz** [comment]
Looks like I just need to add type information to the value being passed to batch (`: _*`). Works now.
