### ISSUE TITLE
adding postgres type cast breaks query parameter binding 

### ISSUE THREAD

**Issue by captify-akraievoy** [scalikejdbc/scalikejdbc#434]
This code, as quoted below, is failing with 
```
java.lang.IllegalStateException: Passed named parameter is ignored. ('afterEpoch)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$1.apply(SQL.scala:74) ~[scalikejdbc-core_2.10-2.2.7.jar:2.2.7]
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$1.apply(SQL.scala:68) ~[scalikejdbc-core_2.10-2.2.7.jar:2.2.7]
```
Weird case, but when you remove `:: timestamp with time zone at time zone 'UTC'` the thing starts working again.
The other workaround is using `bind()` instead of `bindByName()`.

```
        val dateTimeI: DateTime = new DateTime(); // that is a regular Joda DateTime
        SQL(
          s"""
             |select
             |  to_char(
             |    ( to_timestamp(T.beforeEpoch) :: timestamp with time zone at time zone 'UTC' ),
             |    'YYYY-MM-DD HH24:MI:SS tz'
             |  ),
             |  to_char(
             |    ( to_timestamp(T.afterEpoch) :: timestamp with time zone at time zone 'UTC' ),
             |    'YYYY-MM-DD HH24:MI:SS tz'
             |  )
             |from
             |  (
             |    select {beforeEpoch} as beforeEpoch, {afterEpoch} as afterEpoch
             |  ) as T
            """.stripMargin
        )
          //  bindByName went crazy and refused to work for me after
          //    I've added "timestamp with time zone at time zone 'UTC'" to query
          .bindByName(
            'beforeEpoch -> dateTimeI.getMillis / 1000,
            'afterEpoch -> dateTimeI.plusHours(1).getMillis / 1000
          )
          .map(row => row.string(1) -> row.string(2))
          .single()
          .apply()
          .getOrElse(("",""))
      logger.error(s"date params as used in postgres: $dateParams")
```

classpath in the relevant part is like so:
```
SBT: org.scalikejdbc:scalikejdbc-core_2.10:2.2.7:jar
SBT: org.scalikejdbc:scalikejdbc-interpolation-macro_2.10:2.2.7:jar
SBT: org.scalikejdbc:scalikejdbc-interpolation_2.10:2.2.7:jar
SBT: org.scalikejdbc:scalikejdbc_2.10:2.2.7:jar
SBT: org.postgresql:postgresql:9.4-1201-jdbc41:jar
```

scala version is 2.10.5, postgres version is 9.4, and java is...
```
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by seratch** [comment]
Thanks. I just created a pull request to fix this.
