### ISSUE TITLE
jdbcurl with &connectTimeout=6000&socketTimeout=6000

### ISSUE THREAD

**Issue by windpiger** [scalikejdbc/scalikejdbc#502]
when i use db conf:

db.url = "jdbc:mysql://xxxx.mysql.com:4567/zz?autoReconnect=true&autoReconnectForPools=true&connectTimeout=6000&socketTimeout=6000"
db.user = "xxxxx"
db.password = "xxxx"
db.driver = "com.mysql.jdbc.Driver"
db.poolInitialSize = 10
db.poolMaxSize = 150
db.poolConnectionTimeoutMillis = 5000
db.poolValidationQuery = "select 1 as one"
db.poolFactoryName = "bonecp"

**but almost 1~2 days，the client throw exception：
**
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 6,007 milliseconds ago.  The last packet sent successfully to the server was 6,007 milliseconds ago.
        at sun.reflect.GeneratedConstructorAccessor40.newInstance(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_32] at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_32] at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3457) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3357) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3797) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.ConnectionImpl.isReadOnly(ConnectionImpl.java:3622) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]
        ... 28 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.6.0_32]
        at java.net.SocketInputStream.read(SocketInputStream.java:129) ~[na:1.6.0_32]
        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:100) ~[mysql.mysql-connector-java-5.1.37.jar:5.1.37]

**and lots of exceptions:
**java.sql.SQLException: Timed out waiting for a free available connection.

**I think this exception is related to the setting (&socketTimeout=6000) in the url, how can i avoid these exception?**

**Comment by seratch** [comment]
How about removing the parameter or increasing the value?

**Comment by windpiger** [comment]
if the connect of the pool is idle for >6000ms ,can it also cause this exception?
if I remove the parameter,it will wait forever and hang on the db ops

**Comment by seratch** [comment]
The socketTimeout affects long SQL execution. The connectTimeout may affect when your connection pool aquires new connetion or reconnect.
https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
Idling connection in pool just waits forever until it'll be borrowed.

**Comment by windpiger** [comment]
6000ms is too small，so what is the properly value for this parameter？

**Comment by windpiger** [comment]
maybe the pool networks can also cause the sockettimeout ，even it is a short sql，right？

**Comment by seratch** [comment]
If your application normally 1 minute query, over 60000 is appropriate.
N/W trouble happened during SQL execution is another error pattern.

BTW, our community can answer your question not here but at our Google group ML.
I'd like to close this ticket because your topic looks not an issue of scalikejdbc library but a general question. Would you mind closing this?

**Comment by windpiger** [comment]
ok,thanks~
