### ISSUE TITLE
SQL interpolation with PointFromText('POINT(?, ?)') function in MariaDB

### ISSUE THREAD

**Issue by cristianspinetta** [scalikejdbc/scalikejdbc#561]
how can I perform this query in MariaDB with scalike?

`insert into geo_node (point, lat, lng) values (PointFromText('POINT(23.15, -52.1)'), 15, 13);`

I'm trying to do:

```
sql"""insert into geo_node (point, lat, lng) values (PointFromText('POINT(${geoNode.point.latitude} ${geoNode.point.longitude})'), ${geoNode.point.latitude}, ${geoNode.point.longitude})"""
```

But I get:

```
2016-09-01 15:52:03 [ForkJoinPool-1-worker-7] ERROR scalikejdbc.ActiveSession - Failed preparing the statement (Reason: Could not set parameter at position 3, parameter length is 2):

  
insert into geo_node (point, lat, lng)
values (PointFromText('POINT(? ?)'), ?, ?)

2016-09-01 15:52:03 [main] INFO  playground.DBTest$ - Inserted 10000 rows to Geo Node table in 612 ms.
Exception in thread "main" java.sql.SQLException: Could not set parameter at position 3, parameter length is 2
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getSqlException(ExceptionMapper.java:149)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.setParameter(MariaDbServerPreparedStatement.java:151)
	at org.mariadb.jdbc.AbstractMariaDbPrepareStatement.setDouble(AbstractMariaDbPrepareStatement.java:1322)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setDouble(DelegatingPreparedStatement.java:129)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setDouble(DelegatingPreparedStatement.java:129)
	at scalikejdbc.StatementExecutor.scalikejdbc$StatementExecutor$$bind(StatementExecutor.scala:88)
	at scalikejdbc.StatementExecutor$$anonfun$bindParams$2.apply(StatementExecutor.scala:67)
	at scalikejdbc.StatementExecutor$$anonfun$bindParams$2.apply(StatementExecutor.scala:66)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at scalikejdbc.StatementExecutor.bindParams(StatementExecutor.scala:66)
	at scalikejdbc.StatementExecutor.initialize(StatementExecutor.scala:50)
	at scalikejdbc.StatementExecutor.<init>(StatementExecutor.scala:44)
	at scalikejdbc.DBSession$class.createStatementExecutor(DBSession.scala:103)
	at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:469)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:706)
	at scalikejdbc.DBSession$class.updateAndReturnSpecifiedGeneratedKey(DBSession.scala:564)
	at scalikejdbc.ActiveSession.updateAndReturnSpecifiedGeneratedKey(DBSession.scala:706)
	at scalikejdbc.SQLUpdateWithGeneratedKey$$anonfun$10.apply(SQL.scala:646)
	at scalikejdbc.SQLUpdateWithGeneratedKey$$anonfun$10.apply(SQL.scala:646)
	at scalikejdbc.DBConnection$$anonfun$autoCommit$1.apply(DBConnection.scala:221)
	at scalikejdbc.DBConnection$$anonfun$autoCommit$1.apply(DBConnection.scala:221)
	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
	at scalikejdbc.NamedDB.using(NamedDB.scala:17)
	at scalikejdbc.DBConnection$class.autoCommit(DBConnection.scala:221)
	at scalikejdbc.NamedDB.autoCommit(NamedDB.scala:17)
	at scalikejdbc.SQLUpdateWithGeneratedKey.apply(SQL.scala:650)
	at playground.model.GeoNodeRepository$.create(GeoNode.scala:54)
	at playground.DBTest$$anonfun$3.apply(DBTest.scala:28)
	at playground.DBTest$$anonfun$3.apply(DBTest.scala:27)
```

**Comment by cristianspinetta** [comment]
I found a workaround that work fine to me:
```
sql"""insert into geo_node (point, lat, lng) values (PointFromText(${sqlPoint}), ${geoNode.point.latitude}, ${geoNode.point.longitude})"""
```

where `sqlPoint = "POINT(12 15)"`

That works fine because the provided parameter is treated as a string, ie something like `'point(1.0 1.0)'` adding its quotes.
However, I would like to know how is possible to provide a sql function such as `PointFromText('POINT(1.0 1.0)')` as a parameter for statement through scalike. Thanks!

**Comment by seratch** [comment]
sqls"..." returns an SQLSyntax object. SQLSyntax is not a bind parameter but a part of SQL statement which holds bind parameters.
- http://scalikejdbc.org/documentation/sql-interpolation.html#sqlsyntax
- https://github.com/scalikejdbc/scalikejdbc/blob/2.4.2/scalikejdbc-core/src/main/scala/scalikejdbc/SQLInterpolationString.scala#L19-L30

You can build SQLSyntax like this:

```scala
val point = sqls"PointFromText(POINT(12 15))"
val q = sql"""insert into geo_node (point) values ($point)"""
q.statement // insert into geo_node (point) values (PointFromText(POINT(12 15)))
```

But you cannot change the `12 15` runtime in the above example. 
You must be careful to use the API but SQLSyntax.createUnsafely allows you to embed any string inpto ScalikeJDBC's SQL objects.

```scala 
val (lat, long) = (12, 15)
val point = SQLSyntax.createUnsafely(s"PointFromText(POINT($lat $long))")
val q = sql"""insert into geo_node (point) values ($point)"""
q.statement // insert into geo_node (point) values (PointFromText(POINT(12 15)))
```

**Comment by cristianspinetta** [comment]
@seratch excellent!! That worked very well, thanks!

**Comment by seratch** [comment]
@cristianspinetta Would you mind closing this issue now?

**Comment by cristianspinetta** [comment]
yes, of course!
