### ISSUE TITLE
DB_SessionOperationSpec failure in 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [scalikejdbc/scalikejdbc#574]
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/865/consoleFull

```
[scalikejdbc] [info] DB_SessionOperationSpec:
[scalikejdbc] [info] DB(Session operation)
[scalikejdbc] [info] - should be available
[scalikejdbc] [info] - should be impossible to call #begin twice
[scalikejdbc] [info] - should be possible to call #beginIfNotYet several times
[scalikejdbc] [info] #tx
[scalikejdbc] [info] - should not be available before beginning tx *** FAILED ***
[scalikejdbc] [info]   java.lang.IllegalStateException: Connection pool is not yet initialized.(name:'named)
[scalikejdbc] [info]   at scalikejdbc.ConnectionPool$.$anonfun$get$1(ConnectionPool.scala:76)
[scalikejdbc] [info]   at scala.Option.getOrElse(Option.scala:121)
[scalikejdbc] [info]   at scalikejdbc.ConnectionPool$.get(ConnectionPool.scala:74)
[scalikejdbc] [info]   at scalikejdbc.ConnectionPool$.apply(ConnectionPool.scala:65)
[scalikejdbc] [info]   at scalikejdbc.DB_SessionOperationSpec.$anonfun$new$8(DB_SessionOperationSpec.scala:49)
[scalikejdbc] [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[scalikejdbc] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[scalikejdbc] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[scalikejdbc] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[scalikejdbc] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[scalikejdbc] [info]   ...
```

seems to be intermittent. if we keep seeing it, we'll have to disable your test suite

**Comment by seratch** [comment]
@SethTisue Thank you for notifying us. I'll check.

**Comment by SethTisue** [comment]
this is continuing to fail in the 2.12 community build on a fairly regular basis. if you can't do something about it your end pretty soon, we will disable running your tests as part of the community build.

**Comment by SethTisue** [comment]
most recently, from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1029/consoleFull:

```
[scalikejdbc] [error] Failed tests:
[scalikejdbc] [error] 	scalikejdbc.DB_SessionOperationSpec
[scalikejdbc] [error] 	scalikejdbc.SQLSpec
[scalikejdbc] [error] 	scalikejdbc.NamedDBSpec
[scalikejdbc] [error] 	models.MemberSpec
```

cc @lrytz

**Comment by seratch** [comment]
@SethTisue Hmm, I cannot reproduce the situation on my local machine and Travis CI environment.. Of cource, I'd love to fix the failures.

**Comment by SethTisue** [comment]
disabled in https://github.com/scala/community-builds/pull/422 after two more failed runs last night

**Comment by xuwei-k** [comment]
https://github.com/scala/community-builds/commit/2cbaa43b7ce78453080f29a461433cbaf63c22e5#diff-13924878884a607db34ef8aa8c07a253L678
