### ISSUE TITLE
the reverse enginnering dump `batchInert` method missing empty check.

### ISSUE THREAD

**Issue by wuranbo** [scalikejdbc/scalikejdbc#590]
if the entities is empty, then 

    def batchinsert(entities: Seq[T])(implicit session: DBSession): Seq[Int]

has this error.

```
java.lang.IllegalArgumentException: Binding parameter is missing. ('accountGroupId)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4$$anonfun$apply$6.apply(SQL.scala:84)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4$$anonfun$apply$6.apply(SQL.scala:84)
	at scala.Option.orElse(Option.scala:257)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4.apply(SQL.scala:83)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4.apply(SQL.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scalikejdbc.validateAndConvertToNormalStatement$.apply(SQL.scala:81)
	at scalikejdbc.SQL.batchByName(SQL.scala:254)
```

**Comment by xuwei-k** [comment]
Could you provide more informations?(DDL, database, scala version)
I could not reproduce the error.

**Comment by wuranbo** [comment]
sorry @xuwei-k , too hurry. 

It happend everytime. 

mysql Server version: 5.5.47 

build.sbt: 
   
    "org.scalikejdbc" %% "scalikejdbc"       % "2.3.4",
    "org.scalikejdbc" %% "scalikejdbc-config"  % "2.3.4",
    "org.scalikejdbc" %% "scalikejdbc-test"   % "2.3.4"   % "test",
    "org.hsqldb" % "hsqldb" % "2.3.2",
    "mysql" % "mysql-connector-java" % "5.1.38",
    "com.h2database"  %  "h2"                % "1.4.190",

example: 

scala> import cn.yottabyte.Conf
import cn.yottabyte.Conf

scala> import scalikejdbc._
import scalikejdbc._

scala> import cn.yottabyte.mysql._
import cn.yottabyte.mysql._

scala> Conf.init("/Users/wrb/gist/debug/frontend-80/config/frontend.conf")
Registered connection pool : ConnectionPool(url:jdbc:mysql://192.168.1.80:3306/rizhiyi_system?useSSL=false, user:root) using factory : <default>
Registered singleton connection pool : ConnectionPool(url:jdbc:mysql://192.168.1.80:3306/rizhiyi_system?useSSL=false, user:root)
Registered connection pool : ConnectionPool(url:jdbc:mysql://192.168.1.80:3306/rizhiyi_system?useSSL=false, user:root) using factory : <default>
init config from /Users/wrb/gist/debug/frontend-80/config/frontend.conf succ
parse spray config /Users/wrb/gist/debug/frontend-80/config/frontend.conf succ

scala> import cn.yottabyte.mysql.Alert
import cn.yottabyte.mysql.Alert

scala> DB autoCommit { implicit session => Alert.batchinsert(List[Alert]()) }
java.lang.IllegalArgumentException: Binding parameter is missing. ('name)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4$$anonfun$apply$6.apply(SQL.scala:84)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4$$anonfun$apply$6.apply(SQL.scala:84)
	at scala.Option.orElse(Option.scala:257)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4.apply(SQL.scala:83)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4.apply(SQL.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scalikejdbc.validateAndConvertToNormalStatement$.apply(SQL.scala:81)
	at scalikejdbc.SQL.batchByName(SQL.scala:254)
	at cn.yottabyte.mysql.Alert$.batchinsert(Alert.scala:397)
	at $anonfun$1.apply(<console>:16)
	at $anonfun$1.apply(<console>:16)
	at scalikejdbc.DBConnection$class.autoCommit(DBConnection.scala:222)
	at scalikejdbc.DB.autoCommit(DB.scala:60)
	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:215)
	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:214)
	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
	at scalikejdbc.DB$.using(DB.scala:138)
	at scalikejdbc.DB$.autoCommit(DB.scala:214)
	at .<init>(<console>:16)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:77)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xuwei-k** [comment]
I think `the entities is empty` is not error reason.

This changes https://github.com/xuwei-k/scalikejdbc/commit/eeb7fba8dfac47efdf1 pass the test.

**Comment by wuranbo** [comment]
@xuwei-k  try List[Programmer]() ?

**Comment by wuranbo** [comment]
it is my code.

def batchinsert(entities: Seq[Alert])(implicit session: DBSession): Seq[Int] = {
    val params: Seq[Seq[(Symbol, Any)]] = entities.map(entity =>
      Seq(
        'name -> entity.name,
        'domainId -> entity.domainId,
        'savedSearchId -> entity.savedSearchId,
        'ownerId -> entity.ownerId,
        'email -> entity.email,
        'description -> entity.description,
        'checkInterval -> entity.checkInterval,
        'intervalUnit -> entity.intervalUnit,
        'checkCondition -> entity.checkCondition,
        'enabled -> entity.enabled,
        'lastRunTimestamp -> entity.lastRunTimestamp,
        'runResults -> entity.runResults,
        'category -> entity.category,
        'emailGuide -> entity.emailGuide,
        'crontab -> entity.crontab,
        'extendSavedSearchId -> entity.extendSavedSearchId,
        'restrainInterval -> entity.restrainInterval,
        'nowRestrainInterval -> entity.nowRestrainInterval,
        'maxRestrainInterval -> entity.maxRestrainInterval,
        'alertRelease -> entity.alertRelease,
        'alertMeta -> entity.alertMeta,
        'generate -> entity.generate,
        'level -> entity.level))
        SQL("""insert into Alert(
        name,
        domain_id,
        saved_search_id,
        owner_id,
        email,
        description,
        check_interval,
        interval_unit,
        check_condition,
        enabled,
        last_run_timestamp,
        run_results,
        category,
        email_guide,
        crontab,
        extend_saved_search_id,
        restrain_interval,
        now_restrain_interval,
        max_restrain_interval,
        alert_release,
        alert_meta,
        generate,
        level
      ) values (
        {name},
        {domainId},
        {savedSearchId},
        {ownerId},
        {email},
        {description},
        {checkInterval},
        {intervalUnit},
        {checkCondition},
        {enabled},
        {lastRunTimestamp},
        {runResults},
        {category},
        {emailGuide},
        {crontab},
        {extendSavedSearchId},
        {restrainInterval},
        {nowRestrainInterval},
        {maxRestrainInterval},
        {alertRelease},
        {alertMeta},
        {generate},
        {level}
      )""").batchByName(params: _*).apply()

And I try batchInsert(Nil) it also has

scala> DB autoCommit { implicit session => Alert.batchinsert(Nil) }
java.lang.IllegalArgumentException: Binding parameter is missing. ('name)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4$$anonfun$apply$6.apply(SQL.scala:84)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4$$anonfun$apply$6.apply(SQL.scala:84)
	at scala.Option.orElse(Option.scala:257)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4.apply(SQL.scala:83)
	at scalikejdbc.validateAndConvertToNormalStatement$$anonfun$apply$4.apply(SQL.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scalikejdbc.validateAndConvertToNormalStatement$.apply(SQL.scala:81)
	at scalikejdbc.SQL.batchByName(SQL.scala:254)
	at cn.yottabyte.mysql.Alert$.batchinsert(Alert.scala:397)
	at $anonfun$1.apply(<console>:13)
	at $anonfun$1.apply(<console>:13)
	at scalikejdbc.DBConnection$class.autoCommit(DBConnection.scala:222)
	at scalikejdbc.DB.autoCommit(DB.scala:60)
	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:215)
	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:214)
	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
	at scalikejdbc.DB$.using(DB.scala:138)
	at scalikejdbc.DB$.autoCommit(DB.scala:214)
	at .<init>(<console>:13)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:77)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xuwei-k** [comment]
duplicate https://github.com/scalikejdbc/scalikejdbc/issues/481

please use scalikejdbc 2.3.5 or newer

https://github.com/scalikejdbc/scalikejdbc/commit/17336d065cf479b1ea039af7fc253d3efd99aab9
