### ISSUE TITLE
"Connection is null" when using a NamedDB

### ISSUE THREAD

**Issue by adamw** [scalikejdbc/scalikejdbc#675]
Using Postgres and Scalikejdbc 2.5.1, when running this code snippet:

```
  ConnectionPool.add('tests, "jdbc:postgresql:tests", "postgres", "")
  val db: NamedDB = NamedDB('tests)

  db.readOnly { implicit session => }
  db.readOnly { implicit session => }
```

I'm getting an exception on the second `db.readOnly`:

```
Exception in thread "main" java.sql.SQLException: Connection is null.
	at org.apache.commons.dbcp2.DelegatingConnection.checkOpen(DelegatingConnection.java:612)
	at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:560)
	at scalikejdbc.DBConnection$class.scalikejdbc$DBConnection$$setReadOnly(DBConnection.scala:93)
	at scalikejdbc.DBConnection$class.readOnlySession(DBConnection.scala:185)
	at scalikejdbc.NamedDB.readOnlySession(NamedDB.scala:17)
	at scalikejdbc.DBConnection$$anonfun$readOnly$1.apply(DBConnection.scala:201)
	at scalikejdbc.DBConnection$$anonfun$readOnly$1.apply(DBConnection.scala:201)
	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
	at scalikejdbc.NamedDB.using(NamedDB.scala:17)
	at scalikejdbc.DBConnection$class.readOnly(DBConnection.scala:201)
	at scalikejdbc.NamedDB.readOnly(NamedDB.scala:17)
	at com.softwaremill.sql.ScalikejdbcTests$.main(ScalikejdbcTests.scala:15)
	at com.softwaremill.sql.ScalikejdbcTests.main(ScalikejdbcTests.scala)
```

Any hints where to look for the cause?

**Comment by adamw** [comment]
It seems `NamedDB` should only be used *once*. If I create a new one each time (changing `val db: NamedDB = NamedDB('tests)` to `def db: NamedDB = NamedDB('tests)`), I think it works

**Comment by adamw** [comment]
Ah ... just read http://scalikejdbc.org/documentation/connection-pool.html "Reusing same DB instance several times" :)

Makes sense, as `NamedDB` is a wrapper around a connection, but maybe it would be good to add some warnings in javadocs, or another prominent place, so that it would be more obvious how to use the class?

**Comment by seratch** [comment]
Having a warning comment looks good to me. If you have time, send a pull request to add it.

**Comment by adamw** [comment]
Sure, a very small change, here it is:  https://github.com/scalikejdbc/scalikejdbc/pull/676
