### ISSUE TITLE
handling null value in Teradata 

### ISSUE THREAD

**Issue by rogue-one** [scalikejdbc/scalikejdbc#764]
I am getting the following error when trying to insert a row in database. The Target database is of type Teradata. This issue happens one of the value in the input row Array is `null`. As per the error  scalikejdbc must use the method `setNull` instead of `setObject`.

```
    def writeRow(row: Array[Any]): Unit = {
       if (row.length > 0) {
         NamedDB('target).autoCommit(implicit session => withSQL(insert.into(table).values(row: _*)).update.apply())
       }
     }
```

```
Exception in thread "main" com.teradata.jdbc.jdbc_4.util.JDBCException: [Teradata JDBC Driver] [TeraJDBC 14.00.00.13] [Error 1063] [SQLState HY000] null is not supported as a data value with this variant of the setObject method; use the setNull method or the setObject method with a targetSqlType parameter
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:93)
	at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:63)
	at com.teradata.jdbc.jdbc_4.TDPreparedStatement.setObject(TDPreparedStatement.java:1517)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:189)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.setObject(DelegatingPreparedStatement.java:189)
	at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.setObject(DBConnectionAttributesWiredPreparedStatement.scala:52)
	at scalikejdbc.StatementExecutor.scalikejdbc$StatementExecutor$$bind(StatementExecutor.scala:78)
	at scalikejdbc.StatementExecutor$$anonfun$bindParams$2.apply(StatementExecutor.scala:68)
	at scalikejdbc.StatementExecutor$$anonfun$bindParams$2.apply(StatementExecutor.scala:67)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at scalikejdbc.StatementExecutor.bindParams(StatementExecutor.scala:67)
	at scalikejdbc.StatementExecutor.initialize(StatementExecutor.scala:51)
	at scalikejdbc.StatementExecutor.<init>(StatementExecutor.scala:45)
	at scalikejdbc.DBSession$class.createStatementExecutor(DBSession.scala:96)
	at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:465)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:705)
	at scalikejdbc.DBSession$class.updateWithFilters(DBSession.scala:445)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:705)
	at scalikejdbc.DBSessionWrapper$$anonfun$updateWithFilters$1.apply(DBSessionWrapper.scala:81)
	at scalikejdbc.DBSessionWrapper$$anonfun$updateWithFilters$1.apply(DBSessionWrapper.scala:81)
	at scalikejdbc.DBSessionWrapper$$anonfun$withAttributesSwitchedDBSession$1.apply(DBSessionWrapper.scala:35)
	at scalikejdbc.DBSessionWrapper$$anonfun$withAttributesSwitchedDBSession$1.apply(DBSessionWrapper.scala:34)
	at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
	at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:34)
	at scalikejdbc.DBSessionWrapper.updateWithFilters(DBSessionWrapper.scala:81)
	at scalikejdbc.SQLUpdate.apply(SQL.scala:676)
	at com.groupon.edw.magneto2.salesforce.TargetDBManager$DBWriter$$anonfun$writeRow$1.apply(TargetDBManager.scala:44)
	at com.groupon.edw.magneto2.salesforce.TargetDBManager$DBWriter$$anonfun$writeRow$1.apply(TargetDBManager.scala:44)
	at scalikejdbc.DBConnection$$anonfun$autoCommit$1.apply(DBConnection.scala:232)
	at scalikejdbc.DBConnection$$anonfun$autoCommit$1.apply(DBConnection.scala:232)
	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
	at scalikejdbc.NamedDB.using(NamedDB.scala:20)
	at scalikejdbc.DBConnection$class.autoCommit(DBConnection.scala:232)
	at scalikejdbc.NamedDB.autoCommit(NamedDB.scala:20)
	at com.groupon.edw.magneto2.salesforce.TargetDBManager$DBWriter.writeRow(TargetDBManager.scala:44)
	at com.groupon.edw.magneto2.salesforce.SFToTDRunner$$anonfun$run$1.apply(SFToTDRunner.scala:26)
	at com.groupon.edw.magneto2.salesforce.SFToTDRunner$$anonfun$run$1.apply(SFToTDRunner.scala:26)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.groupon.edw.magneto2.salesforce.SFToTDRunner.run(SFToTDRunner.scala:26)
	at com.groupon.edw.magneto2.Main$.main(Main.scala:27)
	at com.groupon.edw.magneto2.Main.main(Main.scala)
```

**Comment by seratch** [comment]
We don't have a plan to support Teradata, but enabling to use `setNull(key)` instead of `setObject(key, null)` only when a flag in GlobalSettings is true may be reasonable for many cases.

**Comment by rogue-one** [comment]
Thanks for the suggestion I can try submitting a PR for this..

**Comment by rogue-one** [comment]
@seratch instead of having a GlobalSetting entry to switch between using `setNull(key)` and `setObject(key, null)` wouldn't it make sense to always use `setNull(key)` for nulls?

**Comment by seratch** [comment]
@rogue-one unfortunately, setNull doesn't work with other JDBC drivers.

**Comment by seratch** [comment]
As I mentioned above, supporting this JDBC driver could cause breaking changes to the existing apps using other JDBC drivers. We are not planning to work on this at this point. If someone wants to use scalikejdbc code along with Teradata dtabase, please consider maintaining a folk or reusing some parts under the Apache License.
