### ISSUE TITLE
No suitable driver found for jdbc:postgres

### ISSUE THREAD

**Issue by rogers140** [scalikejdbc/scalikejdbc#781]
Scala Version: 2.11.11

built.sbt dependencies:
```
  "org.postgresql"           %  "postgresql"                    % "42.1.4",
  "org.scalikejdbc"          %% "scalikejdbc"                   % "3.1.0",
  "org.scalikejdbc"          %% "scalikejdbc-config"            % "3.1.0",
  "org.scalikejdbc"          %% "scalikejdbc-play-initializer"  % "2.6.0-scalikejdbc-3.1"
```

I have two postgres database that I want to hit, mydb1 is 9.3 and mydb2 is 9.6 version.

Code in class that in charge of building connections `myDatabase1.scala`, and similarly in`myDatabase2.scala` (only the connection name changed to `myDb2`):
```
  Class.forName(config.driver)
  ConnectionPool.add("myDb1", config.url, config.username, config.password)

  // Return a DB connection from connection pool.
  def getDB(): DB = {
    DB(ConnectionPool("myDb1").borrow())
  } // Error here
```
And in configs for database1, database2 is similar except the db url.
```
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5430/mydb1"
  username = "myUser"
  password = "myPassword"
```

ErrorMessage:
```
java.sql.SQLException: No suitable driver found for jdbc:postgres://****
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:77)
        at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
        at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
        at scalikejdbc.Commons2ConnectionPool.borrow(Commons2ConnectionPool.scala:48)
```

**Comment by rogers140** [comment]
I also checked that the driver jar `org.postgresql.postgresql-42.1.4.jar`, it is there, and `java -cp ` has that in path too.

**Comment by seratch** [comment]
>java.sql.SQLException: No suitable driver found for jdbc:postgres://****

should be `jdbc:postgresql://`, not `jdbc:postgres://`.

**Comment by rogers140** [comment]
Exactly! Thanks for pointing this out!
