### ISSUE TITLE
NPE when logging queries in 3.2.0

### ISSUE THREAD

**Issue by adamw** [scalikejdbc/scalikejdbc#832]
With the following settings to log generated sql queries:

```
GlobalSettings.loggingSQLAndTime = LoggingSQLAndTimeSettings(enabled = true, singleLineMode = true, logLevel = 'INFO)
```

I'm getting an NPE:

```
Exception in thread "main" java.lang.NullPointerException
	at scalikejdbc.StatementExecutor.normalize$1(StatementExecutor.scala:156)
	at scalikejdbc.StatementExecutor.toPrintable$1(StatementExecutor.scala:170)
	at scalikejdbc.StatementExecutor.$anonfun$sqlString$2(StatementExecutor.scala:203)
	at scalikejdbc.StatementExecutor.$anonfun$sqlString$2$adapted(StatementExecutor.scala:196)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.immutable.StringOps.foreach(StringOps.scala:29)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.StringOps.map(StringOps.scala:29)
	at scalikejdbc.StatementExecutor.scalikejdbc$StatementExecutor$$singleSqlString$1(StatementExecutor.scala:196)
	at scalikejdbc.StatementExecutor.sqlString$lzycompute(StatementExecutor.scala:237)
	at scalikejdbc.StatementExecutor.scalikejdbc$StatementExecutor$$sqlString(StatementExecutor.scala:141)
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.$anonfun$apply$5(StatementExecutor.scala:323)
	at scalikejdbc.Log.error(Log.scala:66)
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply(StatementExecutor.scala:323)
	at scalikejdbc.StatementExecutor$LoggingSQLIfFailed.apply$(StatementExecutor.scala:317)
	at scalikejdbc.StatementExecutor$$anon$1.apply(StatementExecutor.scala:341)
	at scalikejdbc.StatementExecutor.executeUpdate(StatementExecutor.scala:365)
	at scalikejdbc.DBSession$.$anonfun$executeUpdate$1(DBSession.scala:795)
	at scalikejdbc.DBSession$.$anonfun$executeUpdate$1$adapted(DBSession.scala:795)
	at scalikejdbc.DBSession.$anonfun$updateWithFiltersInternal$1(DBSession.scala:534)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:18)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16)
	at scalikejdbc.ActiveSession.using(DBSession.scala:834)
	at scalikejdbc.DBSession.updateWithFiltersInternal(DBSession.scala:532)
	at scalikejdbc.DBSession.updateWithFilters(DBSession.scala:474)
	at scalikejdbc.DBSession.updateWithFilters$(DBSession.scala:463)
	at scalikejdbc.ActiveSession.updateWithFilters(DBSession.scala:834)
	at scalikejdbc.DBSession.updateAndReturnSpecifiedGeneratedKey(DBSession.scala:661)
	at scalikejdbc.DBSession.updateAndReturnSpecifiedGeneratedKey$(DBSession.scala:632)
	at scalikejdbc.ActiveSession.updateAndReturnSpecifiedGeneratedKey(DBSession.scala:834)
	at scalikejdbc.DBSessionWrapper.$anonfun$updateAndReturnSpecifiedGeneratedKey$1(DBSessionWrapper.scala:92)
	at scalikejdbc.DBSessionWrapper.$anonfun$updateAndReturnSpecifiedGeneratedKey$1$adapted(DBSessionWrapper.scala:92)
	at scalikejdbc.DBSessionWrapper.$anonfun$withAttributesSwitchedDBSession$1(DBSessionWrapper.scala:34)
	at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
	at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:33)
	at scalikejdbc.DBSessionWrapper.updateAndReturnSpecifiedGeneratedKey(DBSessionWrapper.scala:92)
	at scalikejdbc.SQLUpdateWithGeneratedKey.$anonfun$apply$20(SQL.scala:773)
	at scalikejdbc.SQLUpdateWithGeneratedKey.$anonfun$apply$20$adapted(SQL.scala:773)
	at scalikejdbc.SQLUpdateWithGeneratedKey.apply(SQL.scala:780)
	at com.softwaremill.sql.ScalikejdbcTests$.insertCity(ScalikejdbcTests.scala:79)
	at com.softwaremill.sql.ScalikejdbcTests$.$anonfun$insertWithGeneratedId$1(ScalikejdbcTests.scala:86)
	at scalikejdbc.DBConnection.$anonfun$localTx$3(DBConnection.scala:337)
	at scalikejdbc.DBConnection.rollbackIfThrowable(DBConnection.scala:302)
	at scalikejdbc.DBConnection.localTx(DBConnection.scala:331)
	at scalikejdbc.DBConnection.localTx$(DBConnection.scala:326)
	at scalikejdbc.NamedDB.localTx(NamedDB.scala:20)
	at com.softwaremill.sql.ScalikejdbcTests$.insertWithGeneratedId(ScalikejdbcTests.scala:85)
	at com.softwaremill.sql.ScalikejdbcTests$.delayedEndpoint$com$softwaremill$sql$ScalikejdbcTests$1(ScalikejdbcTests.scala:253)
	at com.softwaremill.sql.ScalikejdbcTests$delayedInit$body.apply(ScalikejdbcTests.scala:8)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.softwaremill.sql.ScalikejdbcTests$.main(ScalikejdbcTests.scala:8)
	at com.softwaremill.sql.ScalikejdbcTests.main(ScalikejdbcTests.scala)
```

The problematic line is: https://github.com/softwaremill/scala-sql-compare/blob/master/scalikejdbc/src/main/scala/com/softwaremill/sql/ScalikejdbcTests.scala#L79

This worked fine in 3.0.1

**Comment by seratch** [comment]
This issue has been fixed by #829 and #831. I will release 3.2.1 soon.

**Comment by adamw** [comment]
Ah, thanks for the info!

**Comment by xuwei-k** [comment]
3.2.1 released
https://oss.sonatype.org/content/repositories/releases/org/scalikejdbc/scalikejdbc_2.12/3.2.1/

**Comment by adamw** [comment]
Works, thanks! :)
