### ISSUE TITLE
String interpolation causes failed preparing statement due to invalid value for parameterIndex

### ISSUE THREAD

**Issue by cory-klein** [scalikejdbc/scalikejdbc#868]
My code:

```
    val name = camp.name
    sql"""
         |INSERT INTO CAMPS (NAME) VALUES ('$name')
       """.stripMargin.update.apply()
```

Running this results in the following error:

```
2018-04-24 17:48:53.700 ERROR 48650 --- [nio-8080-exec-2] scalikejdbc.ActiveSession                : Failed preparing the statement (Reason: Invalid value "1" for parameter "parameterIndex" [90008-194]):

  ()

2018-04-24 17:48:53.739 ERROR 48650 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause

org.h2.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.message.DbException.getInvalidValueException(DbException.java:228) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1436) ~[h2-1.4.194.jar:1.4.194]
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:355) ~[h2-1.4.194.jar:1.4.194]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.setString(DelegatingPreparedStatement.java:143) ~[commons-dbcp2-2.1.1.jar:2.1.1]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.setString(DelegatingPreparedStatement.java:143) ~[commons-dbcp2-2.1.1.jar:2.1.1]
	at scalikejdbc.DBConnectionAttributesWiredPreparedStatement.setString(DBConnectionAttributesWiredPreparedStatement.scala:74) ~[scalikejdbc-core_2.12-3.2.3.jar:3.2.3]
	at scalikejdbc.StatementExecutor.bind(StatementExecutor.scala:196) ~[scalikejdbc-core_2.12-3.2.3.jar:3.2.3]
	at scalikejdbc.StatementExecutor.$anonfun$bindParams$3(StatementExecutor.scala:169) ~[scalikejdbc-core_2.12-3.2.3.jar:3.2.3]
	at scalikejdbc.StatementExecutor.$anonfun$bindParams$3$adapted(StatementExecutor.scala:168) ~[scalikejdbc-core_2.12-3.2.3.jar:3.2.3]
```

**Comment by cory-klein** [comment]
Could possibly be an off by one error in StatementExecutor

```
  def bindParams(params: Seq[Any]): Unit = {
    val paramsWithIndices = params.map {
      case option: Option[_] => option.orNull[Any]
      case other => other
    }.zipWithIndex

    for ((param, idx) <- paramsWithIndices) {
      bind(param, idx + 1)
    }
    if (isBatch) {
      batchParamsList += params
    }
  }
```

**Comment by cory-klein** [comment]
This is with `com.h2database:h2:1.4.197` and `org.scalikejdbc:scalikejdbc_2.12:3.2.2`

**Comment by cory-klein** [comment]
Bah, that was it. Thank you.
