### ISSUE TITLE
StackOverflowException with many columns table

### ISSUE THREAD

**Issue by vilinski** [scalikejdbc/scalikejdbc#919]
Hi. I have a table with ~250 columns. Looks like scalac 2.12 or scalikejdbc macros can't handle it. I have already commented out all macros like autoConstruct and autoColumns. But it doesn't help.

Here is a compiler error what I get if I define a case class with more than 116 columns: 

<details><summary>CLICK TO SEE Error:scalac: Error: java.lang.StackOverflowError</summary>
<pre>
Error:scalac: Error: java.lang.StackOverflowError
java.lang.StackOverflowError
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:789)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5723)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5731)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:714)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:789)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4752)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:700)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4754)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4801)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5586)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:789)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5723)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5731)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:714)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:789)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4752)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:700)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4754)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4801)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5586)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:789)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5723)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5731)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:714)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:789)
        ....
</pre>
</details>

Column names at the end of the table are defined like here:
`val columns = (1 to 100).flatMap(i => Seq(f"s$i%02dc", f"nns$i%02d"))`

**Comment by xuwei-k** [comment]
I think this is not scalikejdbc bug. Please increase `-Xss` parameter.

**Comment by xuwei-k** [comment]
reproduce without scalikejdbc

```
$ cat A.scala 
package example

case class A(i1: Int, i2: Int, i3: Int, i4: Int, i5: Int, i6: Int, i7: Int, i8: Int, i9: Int, i10: Int, i11: Int, i12: Int, i13: Int, i14: Int, i15: Int, i16: Int, i17: Int, i18: Int, i19: Int, i20: Int, i21: Int, i22: Int, i23: Int, i24: Int, i25: Int, i26: Int, i27: Int, i28: Int, i29: Int, i30: Int, i31: Int, i32: Int, i33: Int, i34: Int, i35: Int, i36: Int, i37: Int, i38: Int, i39: Int, i40: Int, i41: Int, i42: Int, i43: Int, i44: Int, i45: Int, i46: Int, i47: Int, i48: Int, i49: Int, i50: Int, i51: Int, i52: Int, i53: Int, i54: Int, i55: Int, i56: Int, i57: Int, i58: Int, i59: Int, i60: Int, i61: Int, i62: Int, i63: Int, i64: Int, i65: Int, i66: Int, i67: Int, i68: Int, i69: Int, i70: Int, i71: Int, i72: Int, i73: Int, i74: Int, i75: Int, i76: Int, i77: Int, i78: Int, i79: Int, i80: Int, i81: Int, i82: Int, i83: Int, i84: Int, i85: Int, i86: Int, i87: Int, i88: Int, i89: Int, i90: Int, i91: Int, i92: Int, i93: Int, i94: Int, i95: Int, i96: Int, i97: Int, i98: Int, i99: Int, i100: Int, i101: Int, i102: Int, i103: Int, i104: Int, i105: Int, i106: Int, i107: Int, i108: Int, i109: Int, i110: Int, i111: Int, i112: Int, i113: Int, i114: Int, i115: Int, i116: Int, i117: Int, i118: Int, i119: Int, i120: Int, i121: Int, i122: Int, i123: Int, i124: Int, i125: Int, i126: Int, i127: Int, i128: Int, i129: Int, i130: Int, i131: Int, i132: Int, i133: Int, i134: Int, i135: Int, i136: Int, i137: Int, i138: Int, i139: Int, i140: Int, i141: Int, i142: Int, i143: Int, i144: Int, i145: Int, i146: Int, i147: Int, i148: Int, i149: Int, i150: Int, i151: Int, i152: Int, i153: Int, i154: Int, i155: Int, i156: Int, i157: Int, i158: Int, i159: Int, i160: Int, i161: Int, i162: Int, i163: Int, i164: Int, i165: Int, i166: Int, i167: Int, i168: Int, i169: Int, i170: Int, i171: Int, i172: Int, i173: Int, i174: Int, i175: Int, i176: Int, i177: Int, i178: Int, i179: Int, i180: Int, i181: Int, i182: Int, i183: Int, i184: Int, i185: Int, i186: Int, i187: Int, i188: Int, i189: Int, i190: Int, i191: Int, i192: Int, i193: Int, i194: Int, i195: Int, i196: Int, i197: Int, i198: Int, i199: Int, i200: Int, i201: Int, i202: Int, i203: Int, i204: Int, i205: Int, i206: Int, i207: Int, i208: Int, i209: Int, i210: Int, i211: Int, i212: Int, i213: Int, i214: Int, i215: Int, i216: Int, i217: Int, i218: Int, i219: Int, i220: Int, i221: Int, i222: Int, i223: Int, i224: Int, i225: Int, i226: Int, i227: Int, i228: Int, i229: Int, i230: Int, i231: Int, i232: Int, i233: Int, i234: Int, i235: Int, i236: Int, i237: Int, i238: Int, i239: Int, i240: Int)
$ scala -version
Scala code runner version 2.12.6 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
$ scalac A.scala 
error: java.lang.StackOverflowError
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsPt(AnalyzerPlugins.scala:324)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsPt$(AnalyzerPlugins.scala:322)
	at scala.tools.nsc.Global$$anon$1.pluginsPt(Global.scala:448)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5623)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4752)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:700)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4754)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4801)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5586)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5723)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5729)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5063)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5587)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
```

```
$ export JAVA_OPTS="-Xss6m"
$ scalac A.scala # success
```

**Comment by vilinski** [comment]
ah, thanks, 👍 glad to see `scalikejdbc` isn't guilty :)
